# Site settings
title: Tech Tutorials
email: emrullahluleci@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This web site contains tutorials about frontend, backend and mobile development.
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /blog/:categories/:year/:month/:day/:title.html
url: "http://eluleci.github.io" # the base hostname & protocol for your site
twitter_username: emrullahluleci
github_username:  eluleci

# Build settings
markdown: kramdown
